### ISSUE TITLE
Support for Browser-mode VSCode?

### ISSUE THREAD

**Issue by PeterJCLaw** [pdamianik/folder-archiver#15]
I was wondering whether you had any plans to support browser mode VSCode (https://vscode.dev/ and others; see https://code.visualstudio.com/blogs/2021/10/20/vscode-dev for details) and/or if you'd be open to a PR which added that?

I've not yet looked in detail at how possible this is, though I have a use-case where it would be great to have a zip archive plugin which works in browser VSCode.

(It looks like the `jszip` library you're using for zip archives can run purely in browser, so that part at least seems well placed)

**Comment by pdamianik** [comment]
Great News! I have seen your issue and (at least tried) to make this extension and the zip archive type extension compatible with [vscode web](https://vscode.dev/).
The updates should now be available through the vscode extension marketplace (or through the editor).

If you have any issues while using the web version of the extensions, please create another issue or reply to this one.
Please note issue #16

**Comment by pdamianik** [comment]
I verified that it works on

**Comment by PeterJCLaw** [comment]
Nice one, thanks!

Yup, aside from #16 (I primarily do use Firefox) this works for me :)
